create table "overwurd"."JwtRefreshTokens" (
    "Id" integer generated by default as identity,
    "AccessTokenId" uuid not null,
    "Value" uuid not null,
    "UserId" integer not null,
    "CreatedAt" timestamp with time zone not null,
    "RefreshedAt" timestamp with time zone null,
    "ExpiresAt" timestamp with time zone not null,
    "IsRevoked" boolean not null,

    constraint "PK_JwtRefreshTokens" primary key ("Id"),
    constraint "FK_JwtRefreshTokens_Users_UserId" foreign key ("UserId") references "overwurd"."Users" ("Id") on delete cascade
);

create unique index "IX_JwtRefreshTokens_UserId_Id" on "overwurd"."JwtRefreshTokens" ("UserId", "AccessTokenId");