name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.DEPLOY_API_KEY}}
          heroku_email: ${{secrets.DEPLOY_EMAIL}}
          heroku_app_name: overwurd
          docker_heroku_process_type: web
          branch: main
          usedocker: true
          appdir: src
          docker_build_args: |
            CONNECTION_STRING
            BUILD_NUMBER
        env:
          CONNECTION_STRING: ${{secrets.POSTGRESQL_TEST_CONNECTION_STRING}}
          BUILD_NUMBER: ${{github.run_number}}
